spring.application.name=food-ordering-system

# ================= SERVER =================
server.port=${PORT:8080}

# ================= DATABASE =================
spring.datasource.url=jspring.datasource.url=jdbc:mysql://autorack.proxy.rlwy.net:57882/railway
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ================= JPA =================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

# ================= JWT =================
jwt.secret=VGhpc0lzQVN1cGVyU2VjdXJlS2V5Rm9ySFM1MTJBbGdvcml0aG1UaGF0SXNMb25nRW5vdWdoMTIzNDU2Nzg5MA==
jwt.expiration=86400000

# ================= CORS =================
cors.allowed-origins=*

# ================= EMAIL =================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dhruvr.nayak@gmail.com
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true